<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://soap.crmapi.util.redknee.com/accounts/xsd/Accounts-v1.1" xmlns:cardpackagedtns="http://soap.crmapi.util.redknee.com/cardpackages/xsd/2009/04" xmlns:accountdtns="http://soap.crmapi.util.redknee.com/accounts/xsd/2010/06" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://soap.crmapi.util.redknee.com/accounts/xsd/Accounts-v1.1" xmlns:subscriptionv1_1dtns="http://soap.crmapi.util.redknee.com/subscriptions/xsd/2009/04" xmlns:accountv1_0dtns="http://soap.crmapi.util.redknee.com/accounts/xsd/2009/04" xmlns:dtns="http://soap.crmapi.util.redknee.com/common/xsd/2008/08" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:subscriptiondtns="http://soap.crmapi.util.redknee.com/subscriptions/xsd/2010/06">
  <wsdl:documentation>Accounts API 1.1 for CRMAPI Version 2.2 on June 1st, 2010</wsdl:documentation>
  <wsdl:types>
    <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://soap.crmapi.util.redknee.com/accounts/xsd/Accounts-v1.1">
      <xs:import namespace="http://soap.crmapi.util.redknee.com/common/xsd/2008/08" schemaLocation="AccountService_1.xsd"/>
      <xs:import namespace="http://soap.crmapi.util.redknee.com/accounts/xsd/2009/04" schemaLocation="AccountService_1_2_3.xsd"/>
      <xs:import namespace="http://soap.crmapi.util.redknee.com/accounts/xsd/2010/06" schemaLocation="AccountService_1_2_3_4.xsd"/>
      <xs:import namespace="http://soap.crmapi.util.redknee.com/accounts/extensions/xsd/2010/06" schemaLocation="AccountService_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18.xsd"/>
      <xs:import namespace="http://soap.crmapi.util.redknee.com/subscriptions/xsd/2009/04" schemaLocation="AccountService_1_2_3_4_5_6_7_8_9_10_11_12_13_14.xsd"/>
      <xs:import namespace="http://soap.crmapi.util.redknee.com/subscriptions/xsd/2010/06" schemaLocation="AccountService_1_2_3_4_5_6_7_8_9_10_11_12_13.xsd"/>
      <xs:import namespace="http://soap.crmapi.util.redknee.com/subscriptions/extensions/xsd/2010/06" schemaLocation="AccountService_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20.xsd"/>
      <xs:import namespace="http://soap.crmapi.util.redknee.com/cardpackages/xsd/2009/04" schemaLocation="AccountService_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22.xsd"/>
      <xs:element name="getDetailedAccountBalancesResponse" type="tns:getDetailedAccountBalancesResponse"/>
      <xs:complexType name="getDetailedAccountBalancesResponse">
        <xs:sequence>
          <xs:element minOccurs="0" name="return" nillable="true" type="accountdtns:AccountBalance"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="updateAccountAddExtensionResponse" type="tns:updateAccountAddExtensionResponse"/>
      <xs:complexType name="updateAccountAddExtensionResponse">
        <xs:sequence>
          <xs:element name="return" type="accountdtns:BaseAccountExtensionReference"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="listAccountExtensionsResponse" type="tns:listAccountExtensionsResponse"/>
      <xs:complexType name="listAccountExtensionsResponse">
        <xs:sequence>
          <xs:element maxOccurs="unbounded" minOccurs="0" name="return" type="accountdtns:BaseAccountExtensionReference"/>
        </xs:sequence>
      </xs:complexType>
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="getDetailedAccountBalancesResponse">
    <wsdl:part name="part1" element="tns:getDetailedAccountBalancesResponse"/>
  </wsdl:message>
  <wsdl:message name="updateAccountAddExtensionResponse">
    <wsdl:part name="part1" element="tns:updateAccountAddExtensionResponse"/>
  </wsdl:message>
  <wsdl:message name="listAccountExtensionsResponse">
    <wsdl:part name="part1" element="tns:listAccountExtensionsResponse"/>
  </wsdl:message>
</wsdl:definitions>